server:
  port: 8080
  servlet:
    context-path: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  tomcat:
    max-connections: 2000
  connection-timeout: 2000


rpcScannerPackages: com.example.service
